name: Android CI

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          !~/.gradle/caches/build-cache-*
        key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-deps

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/build-cache-*
        key: gradle-builds-${{ github.sha }}
      
    - name: Build with Gradle
      run: |
        echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
        bash ./gradlew assemble
      env:
        KEYSTORE_PATH: "../keystore.jks"
        KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: prepare upload
      run: |
        getDate=$(TZ=UTC-8 date +%Y-%m-%d)
        getVersion=$(cat ~/work/ModemPro/ModemPro/version.txt)
        echo "date=$getDate" >> $GITHUB_ENV
        echo "version=$getVersion" >> $GITHUB_ENV
        echo "name=ModemPro_'$getVerison'_'$getDate'" >> $GITHUB_ENV
        mv ~/work/ModemPro/ModemPro/app/build/outputs/apk/debug/*.apk ~/work/ModemPro/ModemPro/app/build/outputs/apk/debug/ModemPro_"$getVerison"_"$getDate"_debug.apk
        mv ~/work/ModemPro/ModemPro/app/build/outputs/apk/release/*.apk ~/work/ModemPro/ModemPro/app/build/outputs/apk/release/ModemPro_"$getVerison"_"$getDate"_release.apk
        mkdir -p ~/work/ModemPro/ModemPro/GithubRelease
        cp ~/work/ModemPro/ModemPro/app/build/outputs/apk/debug/*.apk ~/work/ModemPro/ModemPro/GithubRelease
        cp ~/work/ModemPro/ModemPro/app/build/outputs/apk/release/*.apk ~/work/ModemPro/ModemPro/GithubRelease
        touch ~/work/ModemPro/ModemPro/file.log
        echo "ModemPro_'$getVerison'_'$getDate'" > ~/work/ModemPro/ModemPro/file.log
        
    - name: Upload Github Release
      uses: ncipollo/release-action@main
      with:
        artifacts: ~/work/ModemPro/ModemPro/GithubRelease/*
        name: "${{ env.date }}"
        tag: "${{ env.date }}"
        bodyFile: ~/work/ModemPro/ModemPro/file.log
        allowUpdates: true
        artifactErrorsFailBuild: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: ModemPro_Release
        path: "app/build/outputs/apk/release/*.apk"
        
    - name: Upload debug
      uses: actions/upload-artifact@v2
      with:
        name: ModemPro_Debug
        path: "app/build/outputs/apk/debug/*.apk"

    